#!/usr/bin/env bash
#
# codex-review.sh — Run an OpenAI Codex review of an implementation plan and
# append the review to the plan file as a "## Appendix: Codex Review" section.
#
# Per CLAUDE.md §4, plan reviews MUST be produced this way:
#   * via `codex exec` (non-interactive, one-shot, read-only sandbox)
#   * written as an APPENDIX to the plan markdown file (version-controlled)
#   * NOT as an interactive Codex session
#   * NOT via the Codex "bridge" / Codex MCP server / IDE integration
#
# Usage:
#   scripts/codex-review.sh docs/plans/2026-06-07-my-feature.md
#
set -euo pipefail

PLAN_FILE="${1:-}"
if [[ -z "${PLAN_FILE}" ]]; then
  echo "Usage: scripts/codex-review.sh <path-to-plan.md>" >&2
  exit 2
fi
if [[ ! -f "${PLAN_FILE}" ]]; then
  echo "error: plan file not found: ${PLAN_FILE}" >&2
  exit 1
fi
if ! command -v codex >/dev/null 2>&1; then
  echo "error: 'codex' CLI not found. Install the OpenAI Codex CLI:" >&2
  echo "       npm install -g @openai/codex   (or see https://developers.openai.com/codex/cli)" >&2
  exit 127
fi

# Model is overridable; default to a current Codex model.
CODEX_MODEL="${CODEX_REVIEW_MODEL:-gpt-5.3-codex}"

TMP_REVIEW="$(mktemp -t codex-review.XXXXXX)"
cleanup() { rm -f "${TMP_REVIEW}"; }
trap cleanup EXIT

read -r -d '' PROMPT <<'EOF' || true
You are a principal engineer performing a rigorous, skeptical design review of
the implementation plan provided below. Your job is to find problems before any
code is written.

Review for: correctness, completeness, hidden complexity, security, data/privacy
risk, failure modes, testability, rollout/rollback safety, and adherence to the
repository's CLAUDE.md rules (strict version control, mandatory changelog,
surgical/simple changes).

Output ONLY GitHub-flavored Markdown suitable to be pasted verbatim as an
appendix under a plan. Do not edit any files. Use exactly this structure:

### Verdict
One of: Approve / Approve with changes / Request changes — plus one sentence why.

### Strengths
Bullets.

### Issues
Numbered, ordered by severity (Blocker > Major > Minor). Each: the problem, why
it matters, and a concrete recommended fix.

### Test coverage gaps
Bullets — what is untested or under-specified.

### Open questions
Bullets — what the author must clarify.

--- BEGIN PLAN ---
EOF

# Build the full prompt: instructions + the plan contents as context.
FULL_PROMPT="${PROMPT}"$'\n'"$(cat "${PLAN_FILE}")"$'\n'"--- END PLAN ---"

echo ">> Running codex exec (read-only) on ${PLAN_FILE} ..." >&2

# `codex exec`  : non-interactive, one-shot.
# --sandbox read-only         : Codex may read the repo but MUST NOT modify files.
# --skip-git-repo-check       : allow running regardless of git state.
# --output-last-message FILE  : capture ONLY the final review message (stdout/stderr carries progress).
codex exec \
  --model "${CODEX_MODEL}" \
  --sandbox read-only \
  --skip-git-repo-check \
  --output-last-message "${TMP_REVIEW}" \
  "${FULL_PROMPT}" >&2

if [[ ! -s "${TMP_REVIEW}" ]]; then
  echo "error: codex produced an empty review; not modifying ${PLAN_FILE}" >&2
  exit 1
fi

STAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
{
  printf '\n\n---\n\n'
  printf '## Appendix: Codex Review (%s)\n\n' "${STAMP}"
  printf '<!-- Generated by `codex exec` (read-only, non-interactive). Do not hand-edit this appendix. -->\n'
  printf '<!-- Model: %s -->\n\n' "${CODEX_MODEL}"
  cat "${TMP_REVIEW}"
  printf '\n'
} >> "${PLAN_FILE}"

echo ">> Appended Codex review to ${PLAN_FILE}" >&2
echo ">> Review the appendix, resolve blockers, then implement (CLAUDE.md §4)." >&2
